nelmio_cors:
    defaults:
        allow_origin: ['https://ffcvconnect.infinityfreeapp.com']
        allow_credentials: false
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600

    paths:
        '^/api/':
            allow_origin: ['https://ffcvconnect.infinityfreeapp.com']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            max_age: 3600
