nelmio_cors:
    defaults:
        allow_origin: ['*']                # Permite todos los orígenes (útil para pruebas)
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
        allow_credentials: false          # Cambiar a true si usas cookies o autenticación basada en sesión
    paths:
        '^/api/':                        # Aplica estas reglas para rutas que empiezan con /api/
            allow_origin: ['*']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600
            allow_credentials: false
