<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZErAEvV\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZErAEvV/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerZErAEvV.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerZErAEvV\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerZErAEvV\App_KernelProdContainer([
    'container.build_hash' => 'ZErAEvV',
    'container.build_id' => '2d7ff77f',
    'container.build_time' => 1747296286,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZErAEvV');
