<?php

namespace ContainerZErAEvV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClubRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ClubRepository' shared autowired service.
     *
     * @return \App\Repository\ClubRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ClubRepository'] = new \App\Repository\ClubRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
