<?php

namespace ContainerZErAEvV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClubControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ClubController' shared autowired service.
     *
     * @return \App\Controller\ClubController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ClubController'] = $instance = new \App\Controller\ClubController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\ClubRepository'] ?? $container->load('getClubRepositoryService')), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')), ($container->services['lexik_jwt_authentication.jwt_manager'] ?? $container->load('getLexikJwtAuthentication_JwtManagerService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\ClubController', $container));

        return $instance;
    }
}
