<?php

namespace ContainerZErAEvV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJugadoresOfertasRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\JugadoresOfertasRepository' shared autowired service.
     *
     * @return \App\Repository\JugadoresOfertasRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\JugadoresOfertasRepository'] = new \App\Repository\JugadoresOfertasRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
