<?php

namespace ContainerZErAEvV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJugadorRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\JugadorRepository' shared autowired service.
     *
     * @return \App\Repository\JugadorRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\JugadorRepository'] = new \App\Repository\JugadorRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
