<?php

namespace ContainerZErAEvV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOfertaControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\OfertaController' shared autowired service.
     *
     * @return \App\Controller\OfertaController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\OfertaController'] = $instance = new \App\Controller\OfertaController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\OfertaRepository'] ?? $container->load('getOfertaRepositoryService')), ($container->privates['App\\Repository\\ClubRepository'] ?? $container->load('getClubRepositoryService')), ($container->privates['App\\Repository\\JugadoresOfertasRepository'] ?? $container->load('getJugadoresOfertasRepositoryService')), ($container->privates['App\\Repository\\JugadorRepository'] ?? $container->load('getJugadorRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\OfertaController', $container));

        return $instance;
    }
}
