<?php

namespace ContainerZErAEvV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOfertaRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\OfertaRepository' shared autowired service.
     *
     * @return \App\Repository\OfertaRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\OfertaRepository'] = new \App\Repository\OfertaRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
