<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFVEhlTT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFVEhlTT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFVEhlTT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFVEhlTT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFVEhlTT\App_KernelDevDebugContainer([
    'container.build_hash' => 'FVEhlTT',
    'container.build_id' => 'f1583214',
    'container.build_time' => 1747309845,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFVEhlTT');
