<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVT12xg8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVT12xg8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVT12xg8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVT12xg8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVT12xg8\App_KernelDevDebugContainer([
    'container.build_hash' => 'VT12xg8',
    'container.build_id' => 'fd429654',
    'container.build_time' => 1747229934,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVT12xg8');
