<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Jugador extends \App\Entity\Jugador implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'address' => [parent::class, 'address', null, 16],
        "\0".parent::class."\0".'city' => [parent::class, 'city', null, 16],
        "\0".parent::class."\0".'dateOfBirth' => [parent::class, 'dateOfBirth', null, 16],
        "\0".parent::class."\0".'dni' => [parent::class, 'dni', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'lastName' => [parent::class, 'lastName', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'ofertas' => [parent::class, 'ofertas', null, 16],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null, 16],
        'address' => [parent::class, 'address', null, 16],
        'city' => [parent::class, 'city', null, 16],
        'dateOfBirth' => [parent::class, 'dateOfBirth', null, 16],
        'dni' => [parent::class, 'dni', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'lastName' => [parent::class, 'lastName', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'ofertas' => [parent::class, 'ofertas', null, 16],
        'password' => [parent::class, 'password', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
